<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=0"/>

    <?= $head; ?>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/bootstrap/dist/css/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/@fortawesome/fontawesome-free/css/all.min.css"); ?>">

    <link rel="stylesheet" href="<?= asset("/public/assets/css/style.css");?>">
    <link rel="stylesheet" href="<?= asset("/public/assets/css/boot.css");?>">
</head>
</html>
<body>
    <main class="outside_section">
        <article>
            <div class="default-load" v-if="loading" style="display: none;">
                <div class="default-load-box">
                    <div class="default-load-box-circle"></div>
                    <p class="font-weight-bold color-white">Aguarde, carregando...</p>
                </div>
            </div>

            <?= $v->section("content"); ?>
        </article>

        <footer class="footer mt-auto py-3" style="position: fixed; width: 100%; bottom: 0;">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-sm-12 col-md-6 col-lg-6">
                        <span class="fs-14">©  Melques Paiva, All Rights Reserved</span>
                    </div>
                </div>
            </div>
        </footer>
    </main>
</body>