<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=0"/>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/bootstrap/dist/css/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/@fortawesome/fontawesome-free/css/all.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/toastr/build/toastr.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset("/public/assets/css/style.css");?>">
    <link rel="stylesheet" href="<?= asset("/public/assets/css/boot.css");?>">
</head>
</html>

<body style="background-color:#f5f5f5;">
    <main id="app">
        <transition name="slide" mode="out-in">
            <router-view></router-view>
        </transition>
    </main>

    <script>
        const host = '<?= url(); ?>';
    </script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/jquery/dist/jquery.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/vue/dist/vue.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/vue-router/dist/vue-router.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/axios/dist/axios.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/toastr/build/toastr.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . '/bootstrap/dist/js/bootstrap.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset('/public/assets/js/app.js'); ?>"></script>

</body>
