<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=0"/>

    <?= $head; ?>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/bootstrap/dist/css/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/@fortawesome/fontawesome-free/css/all.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/toastr/build/toastr.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset("/public/assets/css/style.css");?>">
    <link rel="stylesheet" href="<?= asset("/public/assets/css/boot.css");?>">
</head>
</html>
<body class="signin-page">
    <div class="default-load">
        <div class="default-load-box">
            <div class="default-load-box-circle"></div>
            <p class="font-weight-bold color-white">Aguarde, carregando...</p>
        </div>
    </div>

    <main class="container form-signin" id="mainSignIn">
        <form v-on:submit.prevent="login" action="" class="text-center">
            <i class="fas fa-hand-holding-heart mb-4" style="font-size: 70px; color: var(--blue);"></i>
            <h1 class="h3 mb-3 fw-normal">Sign In</h1>

            <?= flash(); ?>

            <section class="form-input">
                <i class="fas fa-at"></i>
                <input type="text" id="userName" name="userName" placeholder="User"
                    class="form-control" mandatory="User"/>
            </section>

            <section class="form-input">
                <i class="fas fa-lock-open"></i>
                <input type="password" id="password" name="password" placeholder="Password"
                    class="form-control" mandatory="Password"/>
            </section>

            <button type="submit" class="w-100 btn btn-lg btn-blue mt-3 mb-3">LOGIN</button>

            <a href="<?= url("/register"); ?>" class="w-100 btn btn-sm btn-dark-blue mt-3">Register</a>

            <p class="mt-5 mb-3 text-muted">
                © 2022
            </p>
        </form>
    </main>

    <script>
        const host = '<?= url(); ?>';
    </script>
    <script type="text/javascript" src="<?= asset('/node_modules/jquery/dist/jquery.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset('/node_modules/vue/dist/vue.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset('/node_modules/axios/dist/axios.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset('/node_modules/toastr/build/toastr.min.js')?>"></script>
    <script type="text/javascript" src="<?= asset('public/assets/js/signIn.js'); ?>"></script>
</body>
</html>
